name: flutter_wsd_bridge
publish_to: none
description: "Flutter package for WSD (Web Service Development) JavaScript bridge integration with WebView. Supports event tracking, SDK integration, and H5 hybrid functionality."
version: 1.0.0

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  
  # WebView 组件
  flutter_inappwebview: ^6.1.5
  
  # 设备信息和网络
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  connectivity_plus: ^6.0.1
  flutter_udid: ^2.0.0
  
  # 存储和配置
  shared_preferences: ^2.2.3
  
  # JSON序列化
  json_annotation: ^4.8.1
  
  # 日志
  logger: ^2.0.2

  # 远程配置能力，官方用法，低耦合
  flutter_remote_config:
    git:
      url: https://github.com/gistpage/flutter_remote_config.git
      ref: main

  url_launcher: ^6.1.7
  google_sign_in: 6.1.5
  flutter_facebook_auth: ^7.1.2
  firebase_messaging: ^15.2.9
  adjust_sdk: ^5.4.1
  appsflyer_sdk: ^6.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.9

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_wsd_bridge
        pluginClass: FlutterWsdBridgePlugin
      ios:
        pluginClass: FlutterWsdBridgePlugin
